 server:
   error:
      include-message: always
      include-binding-errors: always
   port: 8084
 spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/registration
    password: 123456a@
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: datkieuptit@gmail.com
    password: Datkieu188
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

# mail:
#   host: localhost
#   port: 1025
#   username: hello
#   password: hello
#   properties:
#     mail:
#       smtp:
#         ssl:
#           trust: "*"
#         auth: true
#         starttls:
#           enable: true
#         connectiontimeout: 5000
#         timeout: 3000
#         writetimeout: 5000
